//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace React_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInfo
    {
        public int Id { get; set; }
        public string SinavAdi { get; set; }
        public Nullable<System.TimeSpan> MaxSure { get; set; }
        public Nullable<int> MaxSoruSayisi { get; set; }
    }
}
