//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace React_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTypeFiveChoseExam
    {
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string CorrectAnswer { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<int> BolgeID { get; set; }
    }
}
